name: UnitTests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install the Apple certificate and provisioning profile
        env:
          DEVELOP_CERTIFICATE_BASE64: ${{ secrets.DEVELOP_APPLE_CERTIFICATE }}
          APPSTORE_CERTIFICATE_BASE64: ${{ secrets.APPSTORE_APPLE_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          DEVELOP_PROVISION_PROFILE_BASE64: ${{ secrets.DEVELOP_PROVISIONING_PROFILE }}
          APP_STORE_PROVISION_PROFILE_BASE64: ${{ secrets.APP_STORE_PROVISIONING_PROFILE }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          # create variables
          DEVELOP_CERTIFICATE_PATH=$RUNNER_TEMP/dev_certificate.p12
          APPSTORE_CERTIFICATE_PATH=$RUNNER_TEMP/app_certificate.p12
          DEV_PP_PATH=$RUNNER_TEMP/dev_prov_profile.mobileprovision
          APP_PP_PATH=$RUNNER_TEMP/app_store__prov_profile.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$DEVELOP_CERTIFICATE_BASE64" | base64 --decode -o $DEVELOP_CERTIFICATE_PATH
          echo -n "$APPSTORE_CERTIFICATE_BASE64" | base64 --decode -o $APPSTORE_CERTIFICATE_PATH
          echo -n "$DEVELOP_PROVISION_PROFILE_BASE64" | base64 --decode -o $DEV_PP_PATH
          echo -n "$APP_STORE_PROVISION_PROFILE_BASE64" | base64 --decode -o $APP_PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $DEVELOP_CERTIFICATE_PATH -P "$CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $APPSTORE_CERTIFICATE_PATH -P "$CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $DEV_PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          cp $APP_PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: UnitTests
        run: xcodebuild test -project ArigatouApp.xcodeproj -scheme ArigatouApp -sdk iphonesimulator -destination platform='iOS Simulator,name=iPhone 15,OS=15.3.0' -allowProvisioningUpdates
