name: UnitTests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install provisioning profile
        run: |
         echo ${{ secrets.DEVELOP_PROVISIONING_PROFILE }} | base64 --decode > dev_prov_profile.mobileprovision

      - name: UnitTests
        run: xcodebuild test -project ArigatouApp.xcodeproj -scheme ArigatouApp -sdk iphonesimulator -destination platform='iOS Simulator,name=iPhone 15,OS=15.3.0' -allowProvisioningUpdates


